### ISSUE TITLE
Node ERROR on latest 3.4 release

### ISSUE THREAD

**Issue by Gusher** [Naurk/TP-Minimal-Controller#1]
Am getting this error with latest Godot release..

--- Debugging process started ---
Godot Engine v3.4.stable.official.206ba70f4 - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL ES Batching: ON
 
--- Debugging process stopped ---
 drivers/gles3/rasterizer_storage_gles3.cpp:507 - Condition "image->is_compressed()" is true. Returned: image
Set load_path
Undo: Set load_path
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 scene/resources/texture.cpp:466 - Condition "!f" is true. Returned: ERR_CANT_OPEN
Set load_path
Set load_path
Set scale
Set scale
Set scale
Set scale
Set scale
Set scale
Translate
Undo: Translate
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
Undo: Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Rename Node
 Found invalid node path 'Armature/Skeleton:root_motion' on node 'Main/Player/AnimationTree2'
Remove Node(s)

**Comment by Naurk** [comment]
This doesn't happen to me. Did you change something? Can you give me some information on your system?

**Comment by Gusher** [comment]
....AM NOT SURE what I did but it's gone.... looks like it's working ok now.. ... btw, thanks for this template, very helpful learning from it...
